name: Continuous integration

on:
  push:
  pull_request:
  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cfn-nag:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - uses: stelligent/cfn_nag@8b5f03da74202ba323a145e9d037ddce6cab9dec # master
      with:
        input_path: labs/unicorn-location-api/template.yaml
    - uses: stelligent/cfn_nag@8b5f03da74202ba323a145e9d037ddce6cab9dec # master
      with:
        input_path: labs/unicorn-location-api/final/unicorn-location-api-final/template.yaml
    - uses: stelligent/cfn_nag@8b5f03da74202ba323a145e9d037ddce6cab9dec # master
      with:
        input_path: labs/unicorn-stock-broker/template.yaml

  build-unicorn-store:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: mvn db-setup
        run: ./mvnw package -f infrastructure/db-setup/pom.xml
        working-directory: ./labs/unicorn-store
      - name: mvn cdk
        run: ./mvnw package -f infrastructure/cdk/pom.xml
        working-directory: ./labs/unicorn-store
      - name: mvn unicorn-store-basic
        run: ./mvnw package -f software/alternatives/unicorn-store-basic/pom.xml
        working-directory: ./labs/unicorn-store
      - name: mvn unicorn-store-spring
        run: ./mvnw package -f software/unicorn-store-spring/pom.xml
        working-directory: ./labs/unicorn-store
      - name: mvn unicorn-store-spring-native-graalvm
        run: ./mvnw package -f software/alternatives/unicorn-store-spring-native-graalvm/pom.xml
        working-directory: ./labs/unicorn-store
      - name: mvn unicorn-store-micronaut
        run: ./mvnw package -f software/alternatives/unicorn-store-micronaut/pom.xml
        working-directory: ./labs/unicorn-store
      - name: install cdk
        run: npm install -g aws-cdk
      - name: synth
        run: cdk synth
        working-directory: ./labs/unicorn-store/infrastructure/cdk

  build-unicorn-location-api:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: mvn initial
      run: mvn package
      working-directory: ./labs/unicorn-location-api/UnicornLocationFunction
    - name: mvn final
      run: mvn package
      working-directory: ./labs/unicorn-location-api/final/unicorn-location-api-final/UnicornLocationFunction

  build-unicorn-stock-broker:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: mvn build
        run: mvn package
        working-directory: ./labs/unicorn-stock-broker